import { existsSync, readdirSync } from "node:fs";
import { readFileSync, writeFileSync } from "@visulima/fs";
import { resolve, join, dirname, basename, relative } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { parseTsFile, traverseAst } from "../utils/ast-scanner.js";
import type { ApiConfig } from "../types/api-config.json.js";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

interface NamedExport {
  name: string;
  kind: "value" | "type";
}

interface SubModuleInfo {
  dirName: string;
  absPath: string;
  valueExports: string[];
  typeExports: string[];
}

// ---------------------------------------------------------------------------
// 常量
// ---------------------------------------------------------------------------

const MARKER = "// Auto-generated by `api-gen barrel` — do not edit manually.";

const SKIP_DIRS = new Set([
  "node_modules", "dist", ".vscode", ".git", "scripts",
  ".next", ".agengt", ".claude", ".lingma", "turbo",
]);

// ---------------------------------------------------------------------------
// AST 辅助
// ---------------------------------------------------------------------------

/** 从单个 .ts 文件提取所有具名导出，区分值/类型 */
function extractFileExports(filePath: string): NamedExport[] {
  try {
    const { program } = parseTsFile(filePath);
    const exports: NamedExport[] = [];

    traverseAst(program, (node) => {
      if (node.type !== "ExportNamedDeclaration") return;

      const isTypeContext = node.exportKind === "type";

      // case: export function / export const / export type / export interface ...
      if (node.declaration) {
        const d = node.declaration;
        const names = extractNamesFromDeclaration(d);
        for (const name of names) {
          exports.push({ name, kind: "value" });
        }
        // Override kind for type declarations
        if (d.type === "TSTypeAliasDeclaration" || d.type === "TSInterfaceDeclaration" || isTypeContext) {
          const lastIdx = exports.length - 1;
          for (let i = exports.length - names.length; i <= lastIdx; i++) {
            exports[i].kind = "type";
          }
        }
        return;
      }

      // case: export { a, b }  or  export type { C, D }
      if (node.specifiers) {
        for (const spec of node.specifiers) {
          if (spec.exported?.type === "Identifier" && spec.exported.name) {
            exports.push({
              name: spec.exported.name,
              kind: spec.exportKind === "type" || isTypeContext ? "type" : "value",
            });
          }
        }
      }
    });

    return exports;
  } catch {
    return [];
  }
}

/** 从声明节点提取变量名列表（处理多 declarator 等） */
function extractNamesFromDeclaration(decl: any): string[] {
  const names: string[] = [];

  if (decl.type === "FunctionDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "VariableDeclaration" && decl.declarations) {
    for (const d of decl.declarations) {
      collectIdNames(d.id, names);
    }
  } else if (decl.type === "TSTypeAliasDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "TSInterfaceDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "ClassDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "TSEnumDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  }

  return names;
}

/** 递归收集 Identifier 名（处理解构、重命名） */
function collectIdNames(id: any, out: string[]) {
  if (!id) return;
  if (id.type === "Identifier") {
    out.push(id.name);
  } else if (id.type === "ObjectPattern" && id.properties) {
    for (const prop of id.properties) {
      collectIdNames(prop.value ?? prop.argument, out);
    }
  } else if (id.type === "ArrayPattern" && id.elements) {
    for (const el of id.elements) {
      collectIdNames(el, out);
    }
  }
}

/** 从已有的 index.ts 中提取所有 re-export 名（用于分组聚合读取子模块导出） */
function extractReExports(filePath: string): NamedExport[] {
  try {
    const { program } = parseTsFile(filePath);
    const exports: NamedExport[] = [];

    traverseAst(program, (node) => {
      if (node.type !== "ExportNamedDeclaration") return;
      if (!node.specifiers) return;

      const isTypeContext = node.exportKind === "type";

      for (const spec of node.specifiers) {
        if (spec.exported?.type === "Identifier" && spec.exported.name) {
          exports.push({
            name: spec.exported.name,
            kind: spec.exportKind === "type" || isTypeContext ? "type" : "value",
          });
        }
      }
    });

    return exports;
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// 安全检查
// ---------------------------------------------------------------------------

function hasAutoGenMarker(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, { encoding: "utf-8" });
  return content.startsWith(MARKER);
}

/** 对比新旧内容，无变化 + 有标记则不写入 */
function shouldWrite(filePath: string, newContent: string): boolean {
  if (!existsSync(filePath)) return true;
  const old = readFileSync(filePath, { encoding: "utf-8" });
  return old !== newContent;
}

// ---------------------------------------------------------------------------
// 代码生成
// ---------------------------------------------------------------------------

function genSubModuleIndex(
  dirPath: string,
  files: { name: string; exports: NamedExport[] }[],
): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");

  // 按文件名排序保证确定性
  const sorted = [...files].sort((a, b) => a.name.localeCompare(b.name));

  for (const f of sorted) {
    const values = f.exports.filter((e) => e.kind === "value").map((e) => e.name);
    const types = f.exports.filter((e) => e.kind === "type").map((e) => e.name);

    if (values.length > 0) {
      lines.push(`import { ${values.join(", ")} } from "./${f.name}";`);
    }
    if (types.length > 0) {
      lines.push(`import type { ${types.join(", ")} } from "./${f.name}";`);
    }
  }

  // Collect all value/type names for export statements
  const allValues = sorted
    .flatMap((f) => f.exports.filter((e) => e.kind === "value"))
    .map((e) => e.name);
  const allTypes = sorted
    .flatMap((f) => f.exports.filter((e) => e.kind === "type"))
    .map((e) => e.name);

  // Deduplicate while preserving order
  const seenV = new Set<string>();
  const dedupedValues = allValues.filter((n) => seenV.has(n) ? false : seenV.add(n));
  const seenT = new Set<string>();
  const dedupedTypes = allTypes.filter((n) => seenT.has(n) ? false : seenT.add(n));

  lines.push("");
  if (dedupedValues.length > 0) {
    lines.push(`export { ${dedupedValues.join(", ")} };`);
  }
  if (dedupedTypes.length > 0) {
    lines.push(`export type { ${dedupedTypes.join(", ")} };`);
  }
  lines.push("");

  return lines.join("\n");
}

function genGroupIndex(modules: SubModuleInfo[]): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");

  const sorted = [...modules].sort((a, b) => a.dirName.localeCompare(b.dirName));

  for (const m of sorted) {
    if (m.valueExports.length > 0) {
      lines.push(`import { ${m.valueExports.join(", ")} } from "./${m.dirName}";`);
    }
    if (m.typeExports.length > 0) {
      lines.push(`import type { ${m.typeExports.join(", ")} } from "./${m.dirName}";`);
    }
  }

  const allValues = sorted.flatMap((m) => m.valueExports);
  const allTypes = sorted.flatMap((m) => m.typeExports);

  const seenV = new Set<string>();
  const dedupedValues = allValues.filter((n) => seenV.has(n) ? false : seenV.add(n));
  const seenT = new Set<string>();
  const dedupedTypes = allTypes.filter((n) => seenT.has(n) ? false : seenT.add(n));

  lines.push("");
  if (dedupedValues.length > 0) {
    lines.push(`export { ${dedupedValues.join(", ")} };`);
  }
  if (dedupedTypes.length > 0) {
    lines.push(`export type { ${dedupedTypes.join(", ")} };`);
  }
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// 核心处理
// ---------------------------------------------------------------------------

/** 处理单个子模块目录（如 utils/pagination/）→ 生成 index.ts */
function processSubModule(
  subDirAbs: string,
  subDirName: string,
  dryRun: boolean,
): SubModuleInfo | null {
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(subDirAbs, { withFileTypes: true });
  } catch {
    return null;
  }

  const tsFiles: { name: string; path: string }[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) continue;
    if (entry.name === "index.ts") continue;
    if (entry.name.endsWith(".d.ts")) continue;
    if (entry.name.endsWith(".test.ts")) continue;
    if (!entry.name.endsWith(".ts")) continue;
    const base = entry.name.replace(/\.ts$/, "");
    tsFiles.push({ name: base, path: join(subDirAbs, entry.name) });
  }

  if (tsFiles.length === 0) return null;

  // Extract exports from each file
  const fileExports: { name: string; exports: NamedExport[] }[] = [];
  for (const f of tsFiles) {
    const exps = extractFileExports(f.path);
    if (exps.length > 0) {
      fileExports.push({ name: f.name, exports: exps });
    }
  }

  if (fileExports.length === 0) return null;

  const content = genSubModuleIndex(subDirAbs, fileExports);
  const indexPath = join(subDirAbs, "index.ts");

  // Safety check: existing index without marker → skip
  if (existsSync(indexPath) && !hasAutoGenMarker(indexPath)) {
    pail.warn(`跳过（手动维护）：${chalk.dim(relative(process.cwd(), indexPath))}`);
    return null;
  }

  // Collect all exports from this sub-module
  const allValues = fileExports
    .flatMap((f) => f.exports.filter((e) => e.kind === "value"))
    .map((e) => e.name);
  const allTypes = fileExports
    .flatMap((f) => f.exports.filter((e) => e.kind === "type"))
    .map((e) => e.name);

  const seenV = new Set<string>();
  const dedupedValues = allValues.filter((n) => seenV.has(n) ? false : seenV.add(n));
  const seenT = new Set<string>();
  const dedupedTypes = allTypes.filter((n) => seenT.has(n) ? false : seenT.add(n));

  if (dryRun) {
    console.log(chalk.dim(`  ~ ${relative(process.cwd(), indexPath)}`));
    console.log(chalk.dim(content.split("\n").slice(0, 4).map((l) => `    ${l}`).join("\n")));
    console.log(chalk.dim(`    ... (${fileExports.length} files, ${dedupedValues.length + dedupedTypes.length} exports)`));
  } else {
    if (!shouldWrite(indexPath, content)) {
      pail.debug(`无变更：${chalk.dim(relative(process.cwd(), indexPath))}`);
    } else {
      writeFileSync(indexPath, content);
      const names = [...dedupedValues, ...dedupedTypes];
      console.log(chalk.green(`  ✓ ${subDirName}`) + chalk.dim(`  (${names.length} exports)`));
    }
  }

  return {
    dirName: subDirName,
    absPath: subDirAbs,
    valueExports: dedupedValues,
    typeExports: dedupedTypes,
  };
}

/** 处理单个组路径（如 packages/contract/src/utils/）→ 先处理子模块，再生成组级 index.ts */
function processGroup(name: string, rootDir: string, dryRun: boolean): void {
  const groupAbs = resolve(process.cwd(), rootDir);

  if (!existsSync(groupAbs)) {
    pail.warn(`目录不存在，跳过：${chalk.dim(rootDir)}`);
    return;
  }

  console.log(chalk.bold(`\n📦 ${name}  (${rootDir})`));

  // Step 1: 扫描一级子目录（子模块）
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(groupAbs, { withFileTypes: true });
  } catch {
    return;
  }

  const subDirs = entries
    .filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name))
    .map((e) => e.name)
    .sort();

  // Step 2: 处理子模块 → 生成子 index + 收集导出
  let modules: SubModuleInfo[] = [];

  if (subDirs.length === 0) {
    // 无子模块目录：把当前目录当扁平模块处理，直接返回（不生成组级 index）
    const mod = processSubModule(groupAbs, name, dryRun);
    if (mod) {
      console.log(chalk.dim(`  ─ 扁平目录，已在同级生成 index.ts`));
    }
    return;
  }

  for (const subDirName of subDirs) {
    const subDirAbs = join(groupAbs, subDirName);
    const mod = processSubModule(subDirAbs, subDirName, dryRun);
    if (mod) {
      modules.push(mod);
    }
  }

  if (modules.length === 0) {
    pail.warn("所有子模块均为空，跳过组级 index");
    return;
  }

  // Step 3: 生成组级 index.ts（汇总所有子模块的导出）
  const groupContent = genGroupIndex(modules);
  const groupIndexPath = join(groupAbs, "index.ts");

  // 检查：如果有人手动写了组级 index 且无标记 → 保护
  if (existsSync(groupIndexPath) && !hasAutoGenMarker(groupIndexPath)) {
    pail.warn(`跳过组级 index（手动维护）：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    return;
  }

  if (dryRun) {
    console.log(chalk.dim(`  ~ ${relative(process.cwd(), groupIndexPath)}`));
    console.log(chalk.dim(groupContent.split("\n").slice(0, 4).map((l) => `    ${l}`).join("\n")));
    console.log(chalk.dim(`    ... (${modules.length} modules, aggregated)`));
  } else {
    if (!shouldWrite(groupIndexPath, groupContent)) {
      pail.debug(`无变更：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    } else {
      writeFileSync(groupIndexPath, groupContent);
      const totalExports = modules.reduce((s, m) => s + m.valueExports.length + m.typeExports.length, 0);
      console.log(chalk.cyan(`  ─ 组级 index 已生成 (${modules.length} 子模块, ${totalExports} 项导出)`));
    }
  }
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export interface BarrelOptions {
  group?: string;
  dryRun?: boolean;
}

export async function barrelCommand(options: BarrelOptions = {}): Promise<void> {
  const configPath = resolve(process.cwd(), ".vscode/api-config.json");
  if (!existsSync(configPath)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-config.json，请先执行 api-gen init"));
    process.exit(1);
  }

  const raw = readFileSync(configPath, { encoding: "utf-8" });
  const config = JSON.parse(raw) as ApiConfig;

  const ei = config.exportIndex;
  if (!ei || !ei.includes?.length) {
    pail.warn(
      "未配置 barrel 导出组。请在 .vscode/api-config.json 中添加 exportIndex，如：\n" +
      chalk.dim(JSON.stringify({ exportIndex: { includes: ["utils"], utils: ["packages/contract/src/utils"] } }, null, 2)),
    );
    return;
  }

  let groupNames = ei.includes;
  if (options.group) {
    if (!groupNames.includes(options.group)) {
      pail.error(`未找到导出组 "${options.group}"。可用组：${groupNames.join(", ")}`);
      return;
    }
    groupNames = [options.group];
  }

  console.log(chalk.bold("\n🔷 api-gen barrel — 桶导出生成"));
  if (options.dryRun) {
    console.log(chalk.yellow("  --dry-run 模式，仅预览不写入\n"));
  }

  let totalPaths = 0;
  for (const name of groupNames) {
    const paths = ei[name];
    if (!paths || paths.length === 0) {
      pail.warn(`"${name}" 未配置路径，跳过。请编辑 exportIndex.${name} 添加路径`);
      continue;
    }
    for (const rootDir of paths) {
      processGroup(name, rootDir, !!options.dryRun);
      totalPaths++;
    }
  }

  const mode = options.dryRun ? "(dry-run)" : "已生成";
  pail.success(`\n  ${mode} ${totalPaths} 个路径的 barrel 导出`);
  console.log(chalk.dim("提示：所有生成文件均带有自动标记，可随时安全地重新运行 `api-gen barrel` 覆盖"));
}

export default async function barrel(options?: BarrelOptions): Promise<void> {
  await barrelCommand(options);
}
