import { existsSync, readdirSync, statSync } from "node:fs";
import { dirname } from "node:path";
import { readFileSync, writeFileSync } from "@visulima/fs";
import { resolve, join, basename, relative } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { parseTsFile, traverseAst } from "../utils/ast-scanner.js";
import { findPrecedingJsDoc, parseJsDocTags } from "../utils/jsdoc-tags.js";
import { isPathLike, scanPathGroupChildren, SKIP_DIRS } from "../utils/export-index.js";
import { ApiConfig } from "../types/api-gen.json.js";


// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

/** 桶导出模式:
 *  - full: 全量导出,所有 export 都进入 barrel(默认,与旧行为一致;
 *          不应用 @internal 过滤,与引入可见性机制之前完全等价)
 *  - lib:  库导出,仅导出带 @public 的符号,@internal 与未标注符号一律排除
 */
export type ExportMode = "full" | "lib";

export interface NamedExport {
  name: string;
  kind: "value" | "type";
  /** 来自符号上方紧邻 JSDoc 块注释的标签名集合(小写) */
  tags: ReadonlySet<string>;
}

interface SubModuleInfo {
  dirName: string;
  absPath: string;
  /** Symbol names re-exported by the sub-barrel (always the full set, so
   *  internal callers like tests can `import { x } from "./folder"`). */
  valueExports: string[];
  typeExports: string[];
  /** Per-symbol TSDoc tags from the source file. The top-level barrel
   *  uses these to honor `--lib` visibility without re-parsing. */
  valueTags: Map<string, ReadonlySet<string>>;
  typeTags: Map<string, ReadonlySet<string>>;
}

// ---------------------------------------------------------------------------
// 常量
// ---------------------------------------------------------------------------

const MARKER = "// Auto-generated by `api-gen barrel` — do not edit manually.";

// ---------------------------------------------------------------------------
// AST 辅助
// ---------------------------------------------------------------------------

/** 解析失败时返回空集合,保持原 barrel 容错语义 */
function getTagsForNode(
  sortedComments: ReadonlyArray<{ type: string; value: string; start: number; end: number }>,
  anchor: { start: number },
): Set<string> {
  const body = findPrecedingJsDoc(sortedComments, anchor.start);
  return body ? parseJsDocTags(body) : new Set();
}

/** 从单个 .ts 文件提取所有具名导出,区分值/类型,并按 mode 过滤可见性 */
export function extractFileExports(filePath: string, mode: ExportMode = "full"): NamedExport[] {
  try {
    const { program, comments } = parseTsFile(filePath);
    const sortedComments = [...comments].sort((a, b) => a.start - b.start);
    const exports: NamedExport[] = [];

    traverseAst(program, (node) => {
      if (node.type !== "ExportNamedDeclaration") return;

      const isTypeContext = node.exportKind === "type";

      // case: export function / export const / export type / export interface ...
      if (node.declaration) {
        const d = node.declaration;
        const declTags = getTagsForNode(sortedComments, d);
        const names = extractNamesFromDeclaration(d);
        for (const name of names) {
          exports.push({ name, kind: "value", tags: declTags });
        }
        // Override kind for type declarations
        if (d.type === "TSTypeAliasDeclaration" || d.type === "TSInterfaceDeclaration" || isTypeContext) {
          const lastIdx = exports.length - 1;
          for (let i = exports.length - names.length; i <= lastIdx; i++) {
            exports[i].kind = "type";
          }
        }
        return;
      }

      // case: export { a, b }  or  export type { C, D }
      if (node.specifiers) {
        for (const spec of node.specifiers) {
          if (spec.exported?.type === "Identifier" && spec.exported.name) {
            const specTags = getTagsForNode(sortedComments, spec);
            exports.push({
              name: spec.exported.name,
              kind: spec.exportKind === "type" || isTypeContext ? "type" : "value",
              tags: specTags,
            });
          }
        }
      }
    });

    return exports.filter((e) => shouldExport(e, mode));
  } catch {
    return [];
  }
}

/** 单一可见性判定入口。
 *  - full 模式: 全部导出(零回归,与引入可见性机制之前完全等价)
 *  - lib  模式: 仅导出 @public;@internal 与未标注符号一律排除
 */
export function shouldExport(symbol: NamedExport, mode: ExportMode): boolean {
  if (mode === "full") return true;
  if (symbol.tags.has("internal")) return false;
  if (symbol.tags.has("public")) return true;
  // lib 模式下未标注 → 不导出
  return false;
}

/** 从声明节点提取变量名列表（处理多 declarator 等） */
function extractNamesFromDeclaration(decl: any): string[] {
  const names: string[] = [];

  if (decl.type === "FunctionDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "VariableDeclaration" && decl.declarations) {
    for (const d of decl.declarations) {
      collectIdNames(d.id, names);
    }
  } else if (decl.type === "TSTypeAliasDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "TSInterfaceDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "ClassDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  } else if (decl.type === "TSEnumDeclaration" && decl.id?.name) {
    names.push(decl.id.name);
  }

  return names;
}

/** 递归收集 Identifier 名（处理解构、重命名） */
function collectIdNames(id: any, out: string[]) {
  if (!id) return;
  if (id.type === "Identifier") {
    out.push(id.name);
  } else if (id.type === "ObjectPattern" && id.properties) {
    for (const prop of id.properties) {
      collectIdNames(prop.value ?? prop.argument, out);
    }
  } else if (id.type === "ArrayPattern" && id.elements) {
    for (const el of id.elements) {
      collectIdNames(el, out);
    }
  }
}

/** 从 package.json 中提取主入口的 dist 路径(`.js` 形式)。 */
function readPackageEntry(pkg: {
  main?: string;
  module?: string;
  exports?: unknown;
}): string | null {
  if (pkg.exports) {
    if (typeof pkg.exports === "string") return pkg.exports;
    if (typeof pkg.exports === "object" && pkg.exports !== null) {
      const dot = (pkg.exports as Record<string, unknown>)["."];
      if (typeof dot === "string") return dot;
      if (dot && typeof dot === "object") {
        const d = dot as Record<string, unknown>;
        const candidate =
          (typeof d.default === "string" && d.default) ||
          (typeof d.import === "string" && d.import) ||
          (typeof d.require === "string" && d.require) ||
          (typeof d.types === "string" && d.types);
        if (candidate) return candidate;
      }
    }
  }
  return pkg.main ?? pkg.module ?? null;
}

/** 向上查找最近的 package.json,返回其绝对路径。 */
function findNearestPackageJson(startDir: string): string | null {
  let dir = resolve(startDir);
  while (true) {
    const candidate = join(dir, "package.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** 把 package.json 入口的 dist 路径映射到源路径(`.js` → `.ts`,`/dist/` → `/src/`)。 */
function mapDistEntryToSource(distEntry: string, pkgDir: string): string {
  const abs = resolve(pkgDir, distEntry);
  return abs.replace(/[\\/]dist[\\/]/, "/src/").replace(/\.js$/, ".ts");
}

/** 给定一个 group 根目录,判断它是否对应 package.json 的主入口 barrel。 */
function isEntryBarrel(groupRoot: string): boolean {
  const pkgPath = findNearestPackageJson(groupRoot);
  if (!pkgPath) return false;
  let pkg: { main?: string; module?: string; exports?: unknown };
  try {
    pkg = JSON.parse(readFileSync(pkgPath, { encoding: "utf-8" })) as typeof pkg;
  } catch {
    return false;
  }
  const distEntry = readPackageEntry(pkg);
  if (!distEntry) return false;
  const pkgDir = dirname(pkgPath);
  const entrySrcAbs = mapDistEntryToSource(distEntry, pkgDir);
  const barrelAbs = resolve(groupRoot, "index.ts");
  return entrySrcAbs === barrelAbs;
}

// ---------------------------------------------------------------------------
// 安全检查
// ---------------------------------------------------------------------------

function hasAutoGenMarker(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, { encoding: "utf-8" });
  return content.startsWith(MARKER);
}

/** 对比新旧内容，无变化 + 有标记则不写入 */
function shouldWrite(filePath: string, newContent: string): boolean {
  if (!existsSync(filePath)) return true;
  const old = readFileSync(filePath, { encoding: "utf-8" });
  return old !== newContent;
}

// ---------------------------------------------------------------------------
// 代码生成
// ---------------------------------------------------------------------------

function genSubModuleIndex(
  files: { name: string; exports: NamedExport[] }[] = [],
  subModules: SubModuleInfo[] = [],
): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");

  // 按文件名排序保证确定性
  const sortedFiles = [...files].sort((a, b) => a.name.localeCompare(b.name));
  const sortedSubs = [...subModules].sort((a, b) => a.dirName.localeCompare(b.dirName));

  for (const f of sortedFiles) {
    const values = f.exports.filter((e) => e.kind === "value").map((e) => e.name);
    const types = f.exports.filter((e) => e.kind === "type").map((e) => e.name);

    if (values.length > 0) {
      lines.push(`export { ${values.join(", ")} } from "./${f.name}";`);
    }
    if (types.length > 0) {
      lines.push(`export type { ${types.join(", ")} } from "./${f.name}";`);
    }
  }

  // 子目录 barrel re-export(递归级联)
  for (const m of sortedSubs) {
    const values = m.valueExports;
    const types = m.typeExports;
    if (values.length > 0) {
      lines.push(`export { ${values.join(", ")} } from "./${m.dirName}";`);
    }
    if (types.length > 0) {
      lines.push(`export type { ${types.join(", ")} } from "./${m.dirName}";`);
    }
  }

  lines.push("");

  return lines.join("\n");
}

function genGroupIndex(
  modules: SubModuleInfo[],
  mode: ExportMode = "full"
): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");

  const sorted = [...modules].sort((a, b) => a.dirName.localeCompare(b.dirName));

  const filterByMode = (
    names: string[],
    tags: Map<string, ReadonlySet<string>>,
    kind: "value" | "type"
  ): string[] => {
    if (mode === "full") return names;
    return names.filter((n) =>
      shouldExport({ name: n, kind, tags: tags.get(n) ?? new Set() }, mode)
    );
  };

  for (const m of sorted) {
    const values = filterByMode(m.valueExports, m.valueTags, "value");
    const types = filterByMode(m.typeExports, m.typeTags, "type");
    if (values.length > 0) {
      lines.push(`export { ${values.join(", ")} } from "./${m.dirName}";`);
    }
    if (types.length > 0) {
      lines.push(`export type { ${types.join(", ")} } from "./${m.dirName}";`);
    }
  }

  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// 核心处理
// ---------------------------------------------------------------------------

/** 处理单个子模块目录（如 utils/pagination/）→ 生成 index.ts */
function processSubModule(
  subDirAbs: string,
  subDirName: string,
  dryRun: boolean,
  mode: ExportMode = "full",
): SubModuleInfo | null {
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(subDirAbs, { withFileTypes: true });
  } catch {
    return null;
  }

  const tsFiles: { name: string; path: string }[] = [];
  const subDirs: string[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) subDirs.push(entry.name);
      continue;
    }
    if (entry.name === "index.ts") continue;
    if (entry.name.endsWith(".d.ts")) continue;
    if (entry.name.endsWith(".test.ts")) continue;
    if (!entry.name.endsWith(".ts")) continue;
    const base = entry.name.replace(/\.ts$/, "");
    tsFiles.push({ name: base, path: join(subDirAbs, entry.name) });
  }

  if (tsFiles.length === 0 && subDirs.length === 0) return null;

  // 1) 松散 .ts 文件 → 自己聚合(始终 full 模式,组织聚合用)
  // 子模块 barrel 是组织用的(让包内/测试 `import { x } from "./folder"` 工作)—
  // 不应用 --lib 过滤。只有顶层的 entry barrel 才用 mode。
  const fileExports: { name: string; exports: NamedExport[] }[] = [];
  for (const f of tsFiles) {
    const exps = extractFileExports(f.path, "full");
    if (exps.length > 0) {
      fileExports.push({ name: f.name, exports: exps });
    }
  }

  // 2) 子目录 barrel 已在 processPathGroup 的循环中按 included 列表顺序写过,
  // 这里直接读它们的 index.ts 拿值/类型导出集,再 from "./subdir" 聚合。
  // 如此实现"递归到底"——每一级目录都有自己的 index.ts,把直接 .ts 文件
  // 和子目录 barrel 一起 re-export,形成级联。
  const subModuleInfos: SubModuleInfo[] = [];
  for (const subName of subDirs) {
    const subIdx = join(subDirAbs, subName, "index.ts");
    if (!existsSync(subIdx)) continue;
    // 已有 index.ts 但无 marker → 跳过(由 processPathGroup 循环单独处理过)
    if (!hasAutoGenMarker(subIdx)) continue;
    const info = readSubModuleInfoFromIndex(subIdx, subName);
    if (info) subModuleInfos.push(info);
  }

  if (fileExports.length === 0 && subModuleInfos.length === 0) return null;

  const indexPath = join(subDirAbs, "index.ts");
  const content = genSubModuleIndex(fileExports, subModuleInfos);
  if (!content) return null;

  // Safety check: existing index without marker → skip
  if (existsSync(indexPath) && !hasAutoGenMarker(indexPath)) {
    pail.warn(`跳过（手动维护）：${chalk.dim(relative(process.cwd(), indexPath))}`);
    return null;
  }

  // Collect all exports from this sub-module, plus per-symbol TSDoc tags so
  // the top-level barrel can apply `--lib` visibility without re-parsing.
  const allValues: string[] = [];
  const allTypes: string[] = [];
  const valueTags = new Map<string, ReadonlySet<string>>();
  const typeTags = new Map<string, ReadonlySet<string>>();

  for (const f of fileExports) {
    for (const e of f.exports) {
      if (e.kind === "value") {
        allValues.push(e.name);
        valueTags.set(e.name, e.tags);
      } else {
        allTypes.push(e.name);
        typeTags.set(e.name, e.tags);
      }
    }
  }
  for (const sub of subModuleInfos) {
    for (const n of sub.valueExports) {
      if (!valueTags.has(n)) valueTags.set(n, sub.valueTags.get(n) ?? new Set());
      allValues.push(n);
    }
    for (const n of sub.typeExports) {
      if (!typeTags.has(n)) typeTags.set(n, sub.typeTags.get(n) ?? new Set());
      allTypes.push(n);
    }
  }

  const seenV = new Set<string>();
  const dedupedValues = allValues.filter((n) => seenV.has(n) ? false : seenV.add(n));
  const seenT = new Set<string>();
  const dedupedTypes = allTypes.filter((n) => seenT.has(n) ? false : seenT.add(n));

  if (dryRun) {
    console.log(chalk.dim(`  ~ ${relative(process.cwd(), indexPath)}`));
    console.log(chalk.dim(content.split("\n").slice(0, 4).map((l) => `    ${l}`).join("\n")));
    const tally = fileExports.length + subModuleInfos.length;
    console.log(chalk.dim(`    ... (${tally} 项, ${dedupedValues.length + dedupedTypes.length} exports)`));
  } else {
    if (!shouldWrite(indexPath, content)) {
      pail.debug(`无变更：${chalk.dim(relative(process.cwd(), indexPath))}`);
    } else {
      writeFileSync(indexPath, content);
      const names = [...dedupedValues, ...dedupedTypes];
      const tag = subModuleInfos.length > 0 && fileExports.length > 0
        ? `${fileExports.length} 文件 + ${subModuleInfos.length} 子模块`
        : subModuleInfos.length > 0
        ? `${subModuleInfos.length} 子模块`
        : `${fileExports.length} 文件`;
      console.log(chalk.green(`  ✓ ${subDirName}`) + chalk.dim(`  (${tag}, ${names.length} exports)`));
    }
  }

  return {
    dirName: subDirName,
    absPath: subDirAbs,
    valueExports: dedupedValues,
    typeExports: dedupedTypes,
    valueTags,
    typeTags,
  };
}

/** 从子目录的 index.ts 提取已生成的导出列表,供父级 barrel 聚合。
 *  这里只解析"export { a, b } from ..."与"export type { X, Y } from ..."两行。 */
function readSubModuleInfoFromIndex(indexPath: string, dirName: string): SubModuleInfo | null {
  let text: string;
  try {
    text = readFileSync(indexPath, { encoding: "utf-8" });
  } catch {
    return null;
  }
  const valueExports: string[] = [];
  const typeExports: string[] = [];
  const valueTags = new Map<string, ReadonlySet<string>>();
  const typeTags = new Map<string, ReadonlySet<string>>();
  // export { a, b } from "...";  → value
  // export type { X, Y } from "...";  → type
  const reValue = /^export\s*\{\s*([^}]+?)\s*\}\s*from\s*["'][^"']+["']\s*;?/gm;
  const reType = /^export\s+type\s*\{\s*([^}]+?)\s*\}\s*from\s*["'][^"']+["']\s*;?/gm;
  let m: RegExpExecArray | null;
  while ((m = reValue.exec(text))) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/)[0].trim();
      if (name) {
        valueExports.push(name);
        valueTags.set(name, new Set());
      }
    }
  }
  while ((m = reType.exec(text))) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/)[0].trim();
      if (name) {
        typeExports.push(name);
        typeTags.set(name, new Set());
      }
    }
  }
  if (valueExports.length === 0 && typeExports.length === 0) return null;
  return {
    dirName,
    absPath: dirname(indexPath),
    valueExports,
    typeExports,
    valueTags,
    typeTags,
  };
}

/** 收集当前目录中 flat .ts 文件的导出，每个文件作为一个独立模块 */
function collectFlatModules(
  dirAbs: string,
  mode: ExportMode = "full",
): SubModuleInfo[] {
  const result: SubModuleInfo[] = [];
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(dirAbs, { withFileTypes: true });
  } catch {
    return result;
  }

  for (const entry of entries) {
    if (entry.isDirectory()) continue;
    if (entry.name === "index.ts") continue;
    if (entry.name.endsWith(".d.ts")) continue;
    if (entry.name.endsWith(".test.ts")) continue;
    if (!entry.name.endsWith(".ts")) continue;

    const base = entry.name.replace(/\.ts$/, "");
    const path = join(dirAbs, entry.name);
    // Flat-file barrels at the top level honor `mode` (a flat `.ts` file IS
    // the public module — no sub-barrel in between to re-export from).
    const exps = extractFileExports(path, mode);
    if (exps.length === 0) continue;

    const valueTags = new Map<string, ReadonlySet<string>>();
    const typeTags = new Map<string, ReadonlySet<string>>();
    for (const e of exps) {
      if (e.kind === "value") {
        valueTags.set(e.name, e.tags);
      } else {
        typeTags.set(e.name, e.tags);
      }
    }

    result.push({
      dirName: base,
      absPath: path,
      valueExports: exps.filter((e) => e.kind === "value").map((e) => e.name),
      typeExports: exps.filter((e) => e.kind === "type").map((e) => e.name),
      valueTags,
      typeTags,
    });
  }

  return result;
}

/** 处理单个组路径（如 packages/contract/src/utils/）→ 先处理子模块，再生成组级 index.ts */
function processGroup(
  name: string,
  rootDir: string,
  dryRun: boolean,
  excludedRaw: string[] = [],
  mode: ExportMode = "full",
): void {
  const groupAbs = resolve(process.cwd(), rootDir);

  if (!existsSync(groupAbs)) {
    pail.warn(`目录不存在，跳过：${chalk.dim(rootDir)}`);
    return;
  }

  // --lib 只应用于 package.json 主入口对应的 barrel;其他 group 始终全量
  const entryMode: ExportMode =
    mode === "lib" && !isEntryBarrel(groupAbs) ? "full" : mode;

  // 计算 groupAbs 下被排除的子目录 basename（基于绝对路径前缀匹配）
  const groupAbsNorm = groupAbs.replace(/[\\/]+$/, "");
  const excludedSubDirNames = new Set<string>();
  for (const raw of excludedRaw) {
    if (!raw.startsWith("!")) continue;
    const rel = raw.slice(1);
    const absP = resolve(process.cwd(), rel);
    if (absP.startsWith(groupAbsNorm + "/") || absP.startsWith(groupAbsNorm + "\\")) {
      const tail = absP.slice(groupAbsNorm.length + 1);
      const firstSeg = tail.split(/[\\/]/)[0];
      if (firstSeg) excludedSubDirNames.add(firstSeg);
    }
  }

  console.log(chalk.bold(`\n📦 ${name}  (${rootDir})`));

  // Step 1: 扫描一级子目录（子模块）
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(groupAbs, { withFileTypes: true });
  } catch {
    return;
  }

  const subDirs = entries
    .filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name) && !excludedSubDirNames.has(e.name))
    .map((e) => e.name)
    .sort();

  // Step 2: 收集所有导出（flat 文件 + 子模块）
  let modules: SubModuleInfo[] = [];

  if (subDirs.length === 0) {
    // 纯扁平目录：沿用现有路径，由 processSubModule 生成 index.ts
    // 子 barrel 始终全量(组织聚合),不被 --lib 过滤
    const mod = processSubModule(groupAbs, name, dryRun, "full");
    if (mod) {
      console.log(chalk.dim(`  ─ 扁平目录，已在同级生成 index.ts`));
    }
    return;
  }

  // 有子模块：同时处理 flat 文件和子模块，汇总到组级 index
  // flat 文件是顶层模块 → 用 entryMode(可能受 --lib 影响)
  // 子模块 barrel → 始终全量(full 模式: 连 @internal 也导出,便于包内引用)
  const flatModules = collectFlatModules(groupAbs, entryMode);
  modules.push(...flatModules);

  for (const subDirName of subDirs) {
    const subDirAbs = join(groupAbs, subDirName);
    const mod = processSubModule(subDirAbs, subDirName, dryRun, "full");
    if (mod) {
      modules.push(mod);
    }
  }

  if (modules.length === 0) {
    pail.warn("所有子模块及 flat 文件均为空，跳过组级 index");
    return;
  }

  // Step 3: 生成组级 index.ts(顶层 barrel,可能受 --lib 过滤)
  const groupContent = genGroupIndex(modules, entryMode);
  const groupIndexPath = join(groupAbs, "index.ts");

  // 检查：如果有人手动写了组级 index 且无标记 → 保护
  if (existsSync(groupIndexPath) && !hasAutoGenMarker(groupIndexPath)) {
    pail.warn(`跳过组级 index（手动维护）：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    return;
  }

  if (dryRun) {
    console.log(chalk.dim(`  ~ ${relative(process.cwd(), groupIndexPath)}`));
    console.log(chalk.dim(groupContent.split("\n").slice(0, 4).map((l) => `    ${l}`).join("\n")));
    console.log(chalk.dim(`    ... (${modules.length} modules, aggregated)`));
  } else {
    if (!shouldWrite(groupIndexPath, groupContent)) {
      pail.debug(`无变更：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    } else {
      writeFileSync(groupIndexPath, groupContent);
      const totalExports = modules.reduce((s, m) => s + m.valueExports.length + m.typeExports.length, 0);
      console.log(chalk.cyan(`  ─ 组级 index 已生成 (${flatModules.length} 文件 + ${subDirs.length} 子模块, ${totalExports} 项导出)`));
    }
  }
}

/** 单个路径项：识别是文件还是目录，文件直接提取 exports，目录走 processSubModule */
function processItemAsModule(
  itemAbs: string,
  dryRun: boolean,
  mode: ExportMode = "full",
): SubModuleInfo | null {
  let st: import("node:fs").Stats;
  try { st = statSync(itemAbs); } catch { return null; }

  if (st.isFile()) {
    // 散 .ts 文件：直接 AST 提取，不写 index.ts
    const base = basename(itemAbs);
    if (!base.endsWith(".ts")) return null;
    if (base.endsWith(".d.ts") || base.endsWith(".test.ts") || base === "index.ts") return null;
    const exps = extractFileExports(itemAbs, mode);
    if (exps.length === 0) return null;
    const valueTags = new Map<string, ReadonlySet<string>>();
    const typeTags = new Map<string, ReadonlySet<string>>();
    for (const e of exps) {
      if (e.kind === "value") {
        valueTags.set(e.name, e.tags);
      } else {
        typeTags.set(e.name, e.tags);
      }
    }
    return {
      dirName: base.replace(/\.ts$/, ""),
      absPath: itemAbs,
      valueExports: exps.filter((e) => e.kind === "value").map((e) => e.name),
      typeExports: exps.filter((e) => e.kind === "type").map((e) => e.name),
      valueTags,
      typeTags,
    };
  }

  if (st.isDirectory()) {
    // 子目录：复用 processSubModule(组织聚合,始终全量不过滤)
    return processSubModule(itemAbs, basename(itemAbs), dryRun, "full");
  }

  return null;
}

/** 处理路径形式组：以组名路径为 groupAbs，对 included 数组每项自识别文件/目录，统一汇总 */
function processPathGroup(
  name: string,
  included: string[],
  dryRun: boolean,
  excludedRaw: string[] = [],
  mode: ExportMode = "full",
): void {
  const groupAbs = resolve(process.cwd(), name);

  if (!existsSync(groupAbs)) {
    pail.warn(`目录不存在，跳过：${chalk.dim(name)}`);
    return;
  }

  // --lib 只应用于 package.json 主入口对应的 barrel;其他 group 始终全量
  const entryMode: ExportMode =
    mode === "lib" && !isEntryBarrel(groupAbs) ? "full" : mode;

  // 计算 groupAbs 下被排除的子项 basename（基于绝对路径前缀匹配）
  const groupAbsNorm = groupAbs.replace(/[\\/]+$/, "");
  const excludedNames = new Set<string>();
  for (const raw of excludedRaw) {
    if (!raw.startsWith("!")) continue;
    const rel = raw.slice(1);
    const absP = resolve(process.cwd(), rel);
    if (absP.startsWith(groupAbsNorm + "/") || absP.startsWith(groupAbsNorm + "\\")) {
      const tail = absP.slice(groupAbsNorm.length + 1);
      const firstSeg = tail.split(/[\\/]/)[0];
      if (firstSeg) excludedNames.add(firstSeg);
    }
  }

  console.log(chalk.bold(`\n📦 ${name}  (${included.length} 个子项)`));

  // 按深度倒序:深的先处理(子目录 barrel 先生成),父级聚合时才读得到。
  // 同深度按字典序,保证确定性。
  const sorted = [...included].sort((a, b) => {
    const da = a.split(/[\\/]/).length;
    const db = b.split(/[\\/]/).length;
    if (da !== db) return db - da;
    return a.localeCompare(b);
  });

  const modules: SubModuleInfo[] = [];
  for (const item of sorted) {
    const baseName = basename(item);
    if (excludedNames.has(baseName)) {
      pail.info(`已排除（配置忽略）：${chalk.dim(item)}`);
      continue;
    }
    const itemAbs = resolve(process.cwd(), item);
    const mod = processItemAsModule(itemAbs, dryRun, entryMode);
    if (!mod) continue;
    // 递归填充时,子项可能是 group 根下的深层路径(如 utils/nested),
    // processItemAsModule 返回的 dirName 只有 basename(会变成 ./nested,
    // 路径对不上组根)。这里覆盖为相对 groupAbs 的正路径,供 genGroupIndex
    // 生成 from "./utils/nested" 这种正确的 import。
    const relFromGroup = relative(groupAbsNorm, itemAbs).replace(/\\/g, "/");
    if (relFromGroup && relFromGroup !== ".") {
      mod.dirName = relFromGroup.replace(/\.ts$/, "");
    }
    modules.push(mod);
  }

  if (modules.length === 0) {
    pail.warn("所有子项均为空，跳过组级 index");
    return;
  }

  // 生成组级 index.ts(汇总所有子项,顶层 barrel,可能受 --lib 过滤)
  const groupContent = genGroupIndex(modules, entryMode);
  const groupIndexPath = join(groupAbs, "index.ts");

  if (existsSync(groupIndexPath) && !hasAutoGenMarker(groupIndexPath)) {
    pail.warn(`跳过组级 index（手动维护）：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    return;
  }

  if (dryRun) {
    console.log(chalk.dim(`  ~ ${relative(process.cwd(), groupIndexPath)}`));
    console.log(chalk.dim(groupContent.split("\n").slice(0, 4).map((l) => `    ${l}`).join("\n")));
    console.log(chalk.dim(`    ... (${modules.length} 项, aggregated)`));
  } else {
    if (!shouldWrite(groupIndexPath, groupContent)) {
      pail.debug(`无变更：${chalk.dim(relative(process.cwd(), groupIndexPath))}`);
    } else {
      writeFileSync(groupIndexPath, groupContent);
      const totalExports = modules.reduce((s, m) => s + m.valueExports.length + m.typeExports.length, 0);
      console.log(chalk.cyan(`  ─ 组级 index 已生成 (${modules.length} 项, ${totalExports} 项导出)`));
    }
  }
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export interface BarrelOptions {
  group?: string;
  dryRun?: boolean;
  /** 库导出模式:仅导出 @public 符号,排除 @internal 与未标注符号 */
  lib?: boolean;
}

export async function barrelCommand(options: BarrelOptions = {}): Promise<void> {
  const configPath = resolve(process.cwd(), ".vscode/api-config.json");
  if (!existsSync(configPath)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-config.json，请先执行 api-gen init"));
    process.exit(1);
  }

  const raw = readFileSync(configPath, { encoding: "utf-8" });
  const config = JSON.parse(raw) as ApiConfig;

  const ei = config.exportIndex;
  if (!ei || !ei.includes?.length) {
    pail.warn(
      "未配置 barrel 导出组。请在 .vscode/api-config.json 中添加 exportIndex，如：\n" +
      chalk.dim(JSON.stringify({ exportIndex: { includes: ["utils"], utils: ["packages/contract/src/utils"] } }, null, 2)),
    );
    return;
  }

  let groupNames = ei.includes;
  if (options.group) {
    if (!groupNames.includes(options.group)) {
      pail.error(`未找到导出组 "${options.group}"。可用组：${groupNames.join(", ")}`);
      return;
    }
    groupNames = [options.group];
  }

  console.log(chalk.bold("\n🔷 api-gen barrel — 桶导出生成"));
  if (options.dryRun) {
    console.log(chalk.yellow("  --dry-run 模式，仅预览不写入\n"));
  }
  if (options.lib) {
    console.log(chalk.yellow("  --lib 模式，仅导出 @public 标记的符号(@internal / 未标注均不导出)\n"));
  }

  const mode: ExportMode = options.lib ? "lib" : "full";

  let totalPaths = 0;
  for (const name of groupNames) {
    const rawPaths = ei[name];
    if (rawPaths == null) {
      // 数组缺失视为空数组,后面统一走"空数组"分支
    }
    const safeRaw = rawPaths ?? [];

    // 拆分包含项与排除项：以 "!" 开头的视为排除
    const excluded: string[] = [];
    const explicitIncluded: string[] = [];
    for (const p of safeRaw) {
      if (p.startsWith("!")) excluded.push(p);
      else explicitIncluded.push(p);
    }
    for (const p of excluded) {
      pail.info(`已排除（配置忽略）：${chalk.dim(p.slice(1))}`);
    }

    if (isPathLike(name)) {
      // 路径形式组：included 是组名下的子内容列表（子目录 + 散文件），
      // 一次性处理整组，汇总到组级 index.ts。
      let included = explicitIncluded;
      if (included.length === 0) {
        // 空数组 → 自动递归展开(无需先跑 sync)。
        // 排除模式去掉 `!` 前缀,共享扫描函数按路径/前缀/basename 匹配。
        const excludePatterns = excluded.map((p) => p.slice(1));
        const groupAbs = resolve(process.cwd(), name);
        if (!existsSync(groupAbs)) {
          pail.warn(`目录不存在，跳过：${chalk.dim(name)}`);
          continue;
        }
        const auto = scanPathGroupChildren(groupAbs, name, { exclude: excludePatterns });
        if (auto.length === 0) {
          pail.warn(`"${name}" 目录下无内容，跳过组`);
          continue;
        }
        included = auto;
        console.log(chalk.green(`  ✓ ${name}: 自动展开 ${auto.length} 个子项`));
        for (const p of auto) {
          console.log(chalk.dim(`    - ${p}`));
        }
      }
      processPathGroup(name, included, !!options.dryRun, excluded, mode);
      totalPaths += included.length;
    } else {
      // 约定名组:空数组依然要警告(约定名组没有"组名路径"可扫)
      if (explicitIncluded.length === 0) {
        pail.warn(`"${name}" 未配置路径，跳过。请编辑 exportIndex.${name} 添加路径`);
        continue;
      }
      for (const rootDir of explicitIncluded) {
        processGroup(name, rootDir, !!options.dryRun, excluded, mode);
        totalPaths++;
      }
    }
  }

  const statusMode = options.dryRun ? "(dry-run)" : "已生成";
  pail.success(`\n  ${statusMode} ${totalPaths} 个路径的 barrel 导出`);
  console.log(chalk.dim("提示：所有生成文件均带有自动标记，可随时安全地重新运行 `api-gen barrel` 覆盖"));
}

export default async function barrel(options?: BarrelOptions): Promise<void> {
  await barrelCommand(options);
}
