import { existsSync, readdirSync } from "node:fs";
import { readFileSync, writeFileSync, ensureDirSync } from "@visulima/fs";
import { resolve, join, basename, dirname } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { scanController, scanAllControllers, type ControllerSpec, type RouteSpec } from "../scanner/controller.js";
import type { ApiGenRootConfig, AppLayout } from "../types/api-gen.json.js";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

export interface GenerateHookOptions {
  domain?: string;
  /** "web" | "b2b-admin"; 缺省 = 同时写两个目标 */
  target?: "web" | "b2b-admin";
}

interface HookEntry {
  /** hook 函数名,如 useCurrentSite */
  fnName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  /** eden 链式访问路径段,不含 eden/api/v1 前缀 */
  edenSegments: string[];
  /** 是否接受 id 参数(动态路径 :id) */
  hasIdParam: boolean;
  /** eden 链尾段名(用于 queryOptions / mutationOptions 选择) */
  edenTail: string;
}

const CWD = process.cwd();
const CONFIG_PATH = resolve(CWD, ".vscode/api-gen.json");
const MARKER = "// Auto-generated by api-gen gen-hook — do not edit manually.";

// ---------------------------------------------------------------------------
// 命名规则
// ---------------------------------------------------------------------------

/** kebab-case → PascalCase */
function kebabToPascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : ""))
    .join("");
}

/**
 * 从 controller 路径 + 路由方法推导 hook 函数名
 *
 * 规则(简化版,与 tradeflow eden-hooks.md 习惯一致):
 * - .get("/")        → useList<Domain>
 * - .get("/current") → useCurrent<Domain>
 * - .get("/:id")     → use<Domain>Detail
 * - .post("/")       → useCreate<Domain>
 * - .post("/:id/x")  → useCreate<Domain>X
 * - .put("/:id")     → useUpdate<Domain>
 * - .patch("/:id")   → useUpdate<Domain>
 * - .delete("/:id")  → useDelete<Domain>
 */
function deriveHookName(
  route: RouteSpec,
  domainPascal: string,
): string {
  const path = route.path;
  const cleanedPath = path.replace(/^\//, "");

  if (route.method === "POST") {
    if (cleanedPath === "" || cleanedPath === "/") return `useCreate${domainPascal}`;
    return `useCreate${domainPascal}${kebabToPascal(cleanedPath)}`;
  }
  if (route.method === "DELETE") {
    return `useDelete${domainPascal}`;
  }
  if (route.method === "PUT" || route.method === "PATCH") {
    return `useUpdate${domainPascal}`;
  }

  // GET
  if (cleanedPath === "" || cleanedPath === "/") return `useList${domainPascal}`;
  if (cleanedPath === "current") return `useCurrent${domainPascal}`;

  // 去掉 :id 等动态参数
  const staticPath = cleanedPath.split("/").filter((s) => !s.startsWith(":")).join("/");
  if (staticPath === "" && cleanedPath.includes(":")) {
    return `use${domainPascal}Detail`;
  }
  return `use${domainPascal}${kebabToPascal(staticPath)}`;
}

/** eden 链式访问段(把 :id 换成 (id) 形式调用) */
function deriveEdenSegments(route: RouteSpec, domainKebab: string): { segs: string[]; hasId: boolean; tail: string } {
  const segs: string[] = [domainKebab];
  const path = route.path.replace(/^\//, "");
  const hasId = path.split("/").some((s) => s.startsWith(":"));
  // 把 :id 转换为 (id) 调用
  const parts = path.split("/").filter(Boolean).map((s) => {
    if (s.startsWith(":")) return `(${s.slice(1)})`;
    return s;
  });
  segs.push(...parts);
  const tail = route.method.toLowerCase();
  return { segs, hasId, tail };
}

// ---------------------------------------------------------------------------
// 渲染 hook 函数
// ---------------------------------------------------------------------------

function renderHook(entry: HookEntry, domainPascal: string): string {
  const edenAccess = `eden.api.v1.${entry.edenSegments.join(".")}.${entry.edenTail}`;

  if (entry.method === "GET") {
    if (entry.hasIdParam) {
      // use<Domain>Detail(id) — eden path 已是 (id) 形式,可直接传字符串
      return [
        `export function ${entry.fnName}(id: string) {`,
        `  const eden = useEden();`,
        `  return useQuery(`,
        `    eden.api.v1.${entry.edenSegments.join(".")}.${entry.edenTail}.queryOptions(`,
        `      { id },`,
        `      { staleTime: 5 * 60 * 1000 }`,
        `    )`,
        `  );`,
        `}`,
      ].join("\n");
    }
    return [
      `export function ${entry.fnName}() {`,
        `  const eden = useEden();`,
        `  return useQuery(`,
        `    eden.api.v1.${entry.edenSegments.join(".")}.${entry.edenTail}.queryOptions(`,
        `      {},`,
        `      { staleTime: 5 * 60 * 1000 }`,
        `    )`,
        `  );`,
        `}`,
    ].join("\n");
  }

  // POST/PUT/PATCH/DELETE — mutation
  return [
    `export function ${entry.fnName}() {`,
    `  const eden = useEden();`,
    `  const qc = useQueryClient();`,
    `  return useMutation({`,
    `    ...eden.api.v1.${entry.edenSegments.join(".")}.${entry.edenTail}.mutationOptions(),`,
    `    onSuccess: () => {`,
    `      toast.success("操作成功");`,
    `      qc.invalidateQueries({ queryKey: eden.api.v1.${entry.edenSegments[0]}.get.queryKey() });`,
    `    },`,
    `    onError: (e: any) => toast.error(e?.value?.title ?? "操作失败"),`,
    `  });`,
    `}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// 文件生成
// ---------------------------------------------------------------------------

function generateHookFile(
  domainKebab: string,
  entries: HookEntry[],
): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");
  lines.push('import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";');
  lines.push('import { useEden } from "@/lib/rpc";');
  lines.push('import { toast } from "sonner";');
  lines.push("");

  for (const e of entries) {
    lines.push(renderHook(e, kebabToPascal(domainKebab)));
    lines.push("");
  }
  return lines.join("\n");
}

function hasMarker(content: string): boolean {
  return content.startsWith(MARKER);
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export async function generateHookCommand(opts: GenerateHookOptions = {}): Promise<void> {
  if (!existsSync(CONFIG_PATH)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-gen.json，请先执行 api-gen info"));
    process.exit(1);
  }

  const raw = readFileSync(CONFIG_PATH);
  const config = JSON.parse(raw) as ApiGenRootConfig;

  // 找 b2b-api app(hook 源)
  const b2bApi = config.apps.find((a) => a.appType === "b2b-api");
  if (!b2bApi || !b2bApi.modulesDir) {
    pail.warn("未找到 b2b-api app(需在 .vscode/api-gen.json 标记 appType=\"b2b-api\")");
    return;
  }

  // 找目标 app(web / b2b-admin)
  const targets: AppLayout[] = config.apps.filter(
    (a) => (a.appType === "web" || a.appType === "b2b-admin") && a.appRoot,
  );
  if (opts.target) {
    const t = targets.find((a) => a.appType === opts.target);
    if (!t) {
      pail.warn(`未找到 appType=${opts.target} 的 app`);
      return;
    }
    targets.length = 0;
    targets.push(t);
  }
  if (targets.length === 0) {
    pail.warn("未找到 web / b2b-admin app,无法生成 hook");
    return;
  }

  const modulesDir = resolve(CWD, b2bApi.modulesDir);
  if (!existsSync(modulesDir)) {
    pail.warn(`b2b-api modules 目录不存在: ${chalk.dim(modulesDir)}`);
    return;
  }

  const controllers = scanAllControllers(modulesDir);
  const filtered = opts.domain
    ? controllers.filter((c) => {
        // c.name 形如 "siteController",domain 形如 "site"
        const domain = c.name.replace(/Controller$/, "").replace(/^./, c => c.toLowerCase());
        return domain === opts.domain;
      })
    : controllers;

  if (filtered.length === 0) {
    pail.warn("未找到 controller(检查 b2b-api 的 modules 目录)");
    return;
  }

  let totalFiles = 0;

  for (const ctrl of filtered) {
    const domainKebab = ctrl.name.replace(/Controller$/, "").replace(/^./, c => c.toLowerCase());
    const domainPascal = kebabToPascal(domainKebab);

    const entries: HookEntry[] = ctrl.routes.map((r) => {
      const { segs, hasId, tail } = deriveEdenSegments(r, domainKebab);
      return {
        fnName: deriveHookName(r, domainPascal),
        method: r.method as HookEntry["method"],
        edenSegments: segs,
        hasIdParam: hasId,
        edenTail: tail,
      };
    });

    const content = generateHookFile(domainKebab, entries);

    for (const target of targets) {
      const hooksDir = resolve(CWD, target.appRoot, "src/hooks/api");
      ensureDirSync(hooksDir);
      const outPath = join(hooksDir, `use-${domainKebab}.ts`);

      // 已存在但无 marker → 手动维护,跳过
      if (existsSync(outPath)) {
        const existing = readFileSync(outPath);
        if (!hasMarker(existing)) {
          pail.warn(`跳过(手动维护): ${chalk.dim(outPath)}`);
          continue;
        }
      }

      writeFileSync(outPath, content);
      totalFiles++;
      console.log(chalk.dim(`  + ${target.appName}/src/hooks/api/use-${domainKebab}.ts  (${entries.length} hooks)`));
    }
  }

  if (totalFiles === 0) {
    pail.warn("未生成任何 hook 文件");
    return;
  }

  pail.success(`已生成 ${totalFiles} 个 hook 文件`);
}

export default async function generateHook(opts?: GenerateHookOptions): Promise<void> {
  await generateHookCommand(opts);
}
