import { existsSync } from "node:fs";
import { readFileSync, writeFileSync, ensureDirSync } from "@visulima/fs";
import { resolve, join } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { scanAllControllers, type RouteSpec } from "../scanner/controller.js";
import type { ApiGenRootConfig, AppLayout } from "../types/api-gen.json.js";

// ---------------------------------------------------------------------------
// server.ts edenPrefix 自动探测
// ---------------------------------------------------------------------------

/**
 * 从 b2b-api `server.ts` 里探测 eden 链前缀,返回 `api.v1` 这样的点分字符串。
 *
 * 匹配规则(基于 Elysia 调用链):
 *   1. `new Elysia({ prefix: "/api" })`      → 顶层 prefix
 *   2. `.group("/v1", ...)`                  → 顶层 .group(...)
 *   3. 拼起来 `api.v1` → eden.api.v1.<domain>...
 *
 * 启发式:只能找到第一个 `new Elysia` 的 prefix 和第一个顶层 `.group(...)`。
 * 复杂链(嵌套 group / 重挂载)请手配 `.vscode/api-gen.json` 的 edenPrefix 字段。
 */
function detectEdenPrefixFromServer(appRoot: string | undefined): string | null {
  if (!appRoot) return null;
  const serverPath = resolve(CWD, appRoot, "src/server.ts");
  if (!existsSync(serverPath)) return null;

  const src = readFileSync(serverPath, "utf-8");
  const parts: string[] = [];

  // 1) new Elysia({ prefix: "/api" })
  const prefixMatch = src.match(/new\s+Elysia\s*\(\s*\{[^}]*prefix\s*:\s*["'`](\/[^"'`]+)["'`]/);
  if (prefixMatch) {
    parts.push(prefixMatch[1].replace(/^\//, "").replace(/\/$/, ""));
  }

  // 2) 顶层 .group("/v1", ...) — 匹配第一个顶层调用(不在其它 group 里)
  const groupMatch = src.match(/^\s*\.group\(\s*["'`](\/[^"'`]+)["'`]/m);
  if (groupMatch) {
    parts.push(groupMatch[1].replace(/^\//, "").replace(/\/$/, ""));
  }

  return parts.length > 0 ? parts.join(".") : null;
}

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

export interface GenerateHookOptions {
  domain?: string;
  /** "web" | "b2b-admin"; 缺省 = 同时写两个目标 */
  target?: "web" | "b2b-admin";
}

interface HookEntry {
  /** hook 函数名,如 useCurrentSite */
  fnName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  /** eden 链式访问路径段,不含 edenPrefix 前缀。
   *  第一个 path-param 段会渲染成 `({ name })` 调用形式,后续直接链。 */
  edenSegments: string[];
  /** 路径里所有 :param 的名字(顺序),供 hook 函数签名引用 */
  paramNames: string[];
  /** eden 链尾段名(用于 queryOptions / mutationOptions 选择) */
  edenTail: string;
}

const CWD = process.cwd();
const CONFIG_PATH = resolve(CWD, ".vscode/api-gen.json");
const MARKER = "// Auto-generated by api-gen gen-hook — do not edit manually.";

// ---------------------------------------------------------------------------
// 命名规则
// ---------------------------------------------------------------------------

/** kebab-case → PascalCase;同时把 `/` 当段分隔(用于 "batch/delete" → "BatchDelete") */
function kebabToPascal(name: string): string {
  return name
    .split(/[-_/]/)
    .map((s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : ""))
    .join("");
}

/** 去掉路径里的所有 `:param` 段(用于 hook 名 / 子路径后缀) */
function stripPathParams(path: string): string {
  return path
    .split("/")
    .filter((s) => !s.startsWith(":"))
    .join("/");
}

/**
 * 从 controller 路径 + 路由方法推导 hook 函数名
 *
 * 规则(简化版,与 tradeflow eden-hooks.md 习惯一致):
 * - .get("/")              → useList<Domain>
 * - .get("/current")       → useCurrent<Domain>
 * - .get("/:id")           → use<Domain>Detail
 * - .post("/")             → useCreate<Domain>
 * - .put("/:id")           → useUpdate<Domain>
 * - .patch("/:id/toggle")  → useUpdate<Domain>Toggle    (带子路径避免重名)
 * - .delete("/:id")        → useDelete<Domain>
 * - .delete("/batch")      → useDelete<Domain>Batch     (带子路径避免重名)
 * - .post("/:id/x")        → useCreate<Domain>X          (带子路径避免重名)
 *
 * 子路径后缀规则:去掉所有 `:param` 段后,剩下非空路径拼到动词后(PascalCase),
 * 这样 PUT /:id 和 PATCH /:id/toggle / DELETE /batch 不会撞同名。
 */
function deriveHookName(
  route: RouteSpec,
  domainPascal: string,
): string {
  const cleanedPath = route.path.replace(/^\//, "");
  // 静态子路径(去掉 :param 后剩的),拼到动词后避免同名冲突
  const staticPath = stripPathParams(cleanedPath);
  const staticPascal = staticPath ? kebabToPascal(staticPath) : "";

  if (route.method === "POST") {
    return `useCreate${domainPascal}${staticPascal}`;
  }
  if (route.method === "DELETE") {
    return `useDelete${domainPascal}${staticPascal}`;
  }
  if (route.method === "PUT" || route.method === "PATCH") {
    return `useUpdate${domainPascal}${staticPascal}`;
  }

  // GET
  if (staticPath === "") {
    // cleanedPath 完全是 :param(无静态段)→ use<Domain>Detail
    if (cleanedPath.includes(":")) return `use${domainPascal}Detail`;
    // cleanedPath === "current" → useCurrent
    if (cleanedPath === "current") return `useCurrent${domainPascal}`;
    // cleanedPath 空 → useList
    return `useList${domainPascal}`;
  }
  if (staticPath === "current") return `useCurrent${domainPascal}`;
  return `use${domainPascal}${staticPascal}`;
}

/** eden 链式访问段
 *
 * 把 :id 转换为 `.({ id })` 调用形式(eden 的实际语法,不是 Elysia 那种 .(id)):
 *   .get("/:id")        → [ad, ({ id }), get]
 *   .patch("/:id/toggle") → [ad, ({ id }), toggle, patch]
 *   .get("/")           → [ad, get]
 *   .delete("/batch")   → [ad, batch, delete]
 *
 * 返回 segments 给 renderHook 拼 `eden.${prefix}.${segs.join(".")}.${tail}`;
 * 第一个 path-param 段必须传对象 `{ name }`,后续方法调用直接链。
 */
function deriveEdenSegments(
  route: RouteSpec,
  domainKebab: string,
): { segs: string[]; tail: string; paramNames: string[] } {
  const segs: string[] = [domainKebab];
  const path = route.path.replace(/^\//, "");
  const paramNames: string[] = [];
  const parts = path.split("/").filter(Boolean).map((s) => {
    if (s.startsWith(":")) {
      const name = s.slice(1);
      paramNames.push(name);
      return `({ ${name} })`;
    }
    return s;
  });
  segs.push(...parts);
  const tail = route.method.toLowerCase();
  return { segs, tail, paramNames };
}

// ---------------------------------------------------------------------------
// 渲染 hook 函数
// ---------------------------------------------------------------------------

/**
 * 渲染单个 hook 函数。
 *
 * @param edenPrefix  Eden 访问链前缀,缺省 ""(直接挂载)。
 *                    - ""  → eden.<domain>.<path>.<method>
 *                    - "api" → eden.api.<domain>.<path>.<method>(server.ts: prefix "/api")
 *                    - "api.v1" → eden.api.v1.<domain>... (多版本)
 *                    该值需与 .vscode/api-gen.json 的 edenPrefix 保持一致。
 */
function renderHook(entry: HookEntry, domainPascal: string, edenPrefix: string): string {
  // eden 链段拼接:含 `-` 的段需要 bracket access(`["sort-order"]`),不能直接 `.sort-order`
  const segs = (edenPrefix ? [edenPrefix, ...entry.edenSegments] : entry.edenSegments)
    .map((s) => (s.includes("-") ? `["${s}"]` : s))
    .join(".");
  const tail = entry.edenTail;

  // hook 函数参数列表:把 paramNames 渲染成函数签名
  // 无参 → `()`(强制,避免 `useFoo {` 这种 JS 语法错误)
  // 单个 :id → `(id: string)`
  // 多个 :userId/:postId → `({ userId, postId }: { userId: string; postId: string })`
  const paramSig =
    entry.paramNames.length === 0
      ? "()"
      : entry.paramNames.length === 1
        ? `(${entry.paramNames[0]}: string)`
        : `({ ${entry.paramNames.join(", ")} }: { ${entry.paramNames.map((n) => `${n}: string`).join("; ")} })`;

  if (entry.method === "GET") {
    return [
      `export function ${entry.fnName}${paramSig} {`,
      `  const eden = useEden();`,
      `  return useQuery(`,
      `    eden.${segs}.${tail}.queryOptions(`,
      `      {},`,
      `      { staleTime: 5 * 60 * 1000 }`,
      `    )`,
      `  );`,
      `}`,
    ].join("\n");
  }

  // POST/PUT/PATCH/DELETE — mutation
  // invalidateQueries 启发式:失效该 domain 根 get 列表
  const rootGet = edenPrefix
    ? `eden.${edenPrefix}.${entry.edenSegments[0]}.get`
    : `eden.${entry.edenSegments[0]}.get`;
  return [
    `export function ${entry.fnName}${paramSig} {`,
    `  const eden = useEden();`,
    `  const qc = useQueryClient();`,
    `  return useMutation({`,
    `    ...eden.${segs}.${tail}.mutationOptions(),`,
    `    onSuccess: () => {`,
    `      toast.success("操作成功");`,
    `      qc.invalidateQueries({ queryKey: ${rootGet}.queryKey() });`,
    `    },`,
    `    onError: (e: any) => toast.error(e?.value?.title ?? "操作失败"),`,
    `  });`,
    `}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// 文件生成
// ---------------------------------------------------------------------------

function generateHookFile(
  domainKebab: string,
  entries: HookEntry[],
  edenPrefix: string,
): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");
  lines.push('import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";');
  lines.push('import { useEden } from "@/lib/rpc";');
  lines.push('import { toast } from "sonner";');
  lines.push("");

  for (const e of entries) {
    lines.push(renderHook(e, kebabToPascal(domainKebab), edenPrefix));
    lines.push("");
  }
  return lines.join("\n");
}

function hasMarker(content: string): boolean {
  return content.startsWith(MARKER);
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export async function generateHookCommand(opts: GenerateHookOptions = {}): Promise<void> {
  if (!existsSync(CONFIG_PATH)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-gen.json，请先执行 api-gen info"));
    process.exit(1);
  }

  const raw = readFileSync(CONFIG_PATH);
  const config = JSON.parse(raw) as ApiGenRootConfig;

  // 找 b2b-api app(hook 源) — 提前到 edenPrefix 探测前用
  const b2bApi = config.apps.find((a) => a.appType === "b2b-api");
  if (!b2bApi || !b2bApi.modulesDir) {
    pail.warn("未找到 b2b-api app(需在 .vscode/api-gen.json 标记 appType=\"b2b-api\")");
    return;
  }

  // Eden 路径前缀:从配置读,缺省自动从 b2b-api server.ts 探测(prefix + 顶层 .group())。
  // 探测失败才退化为 ""(直接挂载)。
  let edenPrefix = config.edenPrefix ?? "";
  if (edenPrefix === "") {
    const detected = detectEdenPrefixFromServer(b2bApi.appRoot);
    if (detected) {
      edenPrefix = detected;
      console.log(chalk.dim(`  探测到 server.ts 路径前缀: eden.${edenPrefix}.*`));
    }
  }

  // 找目标 app(web / b2b-admin)
  const targets: AppLayout[] = config.apps.filter(
    (a) => (a.appType === "web" || a.appType === "b2b-admin") && a.appRoot,
  );
  if (opts.target) {
    const t = targets.find((a) => a.appType === opts.target);
    if (!t) {
      pail.warn(`未找到 appType=${opts.target} 的 app`);
      return;
    }
    targets.length = 0;
    targets.push(t);
  }
  if (targets.length === 0) {
    pail.warn("未找到 web / b2b-admin app,无法生成 hook");
    return;
  }

  const modulesDir = resolve(CWD, b2bApi.modulesDir);
  if (!existsSync(modulesDir)) {
    pail.warn(`b2b-api modules 目录不存在: ${chalk.dim(modulesDir)}`);
    return;
  }

  const controllers = scanAllControllers(modulesDir);
  const filtered = opts.domain
    ? controllers.filter((c) => {
        // c.name 形如 "siteController",domain 形如 "site"
        const domain = c.name.replace(/Controller$/, "").replace(/^./, c => c.toLowerCase());
        return domain === opts.domain;
      })
    : controllers;

  if (filtered.length === 0) {
    pail.warn("未找到 controller(检查 b2b-api 的 modules 目录)");
    return;
  }

  let totalFiles = 0;

  for (const ctrl of filtered) {
    const domainKebab = ctrl.name.replace(/Controller$/, "").replace(/^./, c => c.toLowerCase());
    const domainPascal = kebabToPascal(domainKebab);

    const rawEntries: HookEntry[] = ctrl.routes.map((r) => {
      const { segs, tail, paramNames } = deriveEdenSegments(r, domainKebab);
      return {
        fnName: deriveHookName(r, domainPascal),
        method: r.method as HookEntry["method"],
        edenSegments: segs,
        paramNames,
        edenTail: tail,
      };
    });

    // 去重:极少数 controller 有完全相同 method+path 的路由(IDE 偶发);
    // 同 fnName 重复会触发 TS 重复导出,所以这里去重 + warn。
    const seen = new Set<string>();
    const entries: HookEntry[] = [];
    for (const e of rawEntries) {
      if (seen.has(e.fnName)) {
        pail.warn(`  hook "${e.fnName}" 重复定义,跳过(method=${e.method} path=${e.edenSegments.join("/")})`);
        continue;
      }
      seen.add(e.fnName);
      entries.push(e);
    }

    const content = generateHookFile(domainKebab, entries, edenPrefix);

    for (const target of targets) {
      const hooksDir = resolve(CWD, target.appRoot, "src/hooks/api");
      ensureDirSync(hooksDir);
      const outPath = join(hooksDir, `use-${domainKebab}.ts`);

      // 已存在但无 marker → 手动维护,跳过
      if (existsSync(outPath)) {
        const existing = readFileSync(outPath);
        if (!hasMarker(existing)) {
          pail.warn(`跳过(手动维护): ${chalk.dim(outPath)}`);
          continue;
        }
      }

      writeFileSync(outPath, content);
      totalFiles++;
      console.log(chalk.dim(`  + ${target.appName}/src/hooks/api/use-${domainKebab}.ts  (${entries.length} hooks)`));
    }
  }

  if (totalFiles === 0) {
    pail.warn("未生成任何 hook 文件");
    return;
  }

  pail.success(`已生成 ${totalFiles} 个 hook 文件`);
  if (edenPrefix) {
    pail.info(`Eden prefix: ${chalk.cyan(edenPrefix)} (来自 .vscode/api-gen.json)`);
  }
}

export default async function generateHook(opts?: GenerateHookOptions): Promise<void> {
  await generateHookCommand(opts);
}
