import { existsSync } from "node:fs";
import { readFileSync, writeFileSync } from "@visulima/fs";
import { resolve, join } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { parseTsFile, traverseAst } from "../utils/ast-scanner.js";
import type { ApiGenRootConfig } from "../types/api-gen.json.js";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

export interface GenerateTbschemaOptions {
  /** 指定单个 domain(对应 dbschema 表名去掉 Table 后缀的 kebab 名) */
  domain?: string;
  /** 覆盖已有 tbschema 文件 */
  force?: boolean;
}

interface TableInfo {
  /** 导出变量名,如 "heroCardTable" */
  varName: string;
  /** Pascal 短名,如 "HeroCard" */
  pascalName: string;
  /** kebab-case 文件名,如 "hero-card" */
  fileName: string;
}

const CWD = process.cwd();
const CONFIG_PATH = resolve(CWD, ".vscode/api-gen.json");
const MARKER = "// Auto-generated by api-gen gen-tbschema — do not edit manually.";

// ---------------------------------------------------------------------------
// 辅助
// ---------------------------------------------------------------------------

/** OXc 判断是否为 pgTable(...) 调用(支持 pgTable(...) 和 p.pgTable(...) 两种形式) */
function isPgTableCall(node: any): boolean {
  if (node?.type !== "CallExpression") return false;
  const callee = node.callee;
  if (callee?.type === "Identifier" && callee.name === "pgTable") return true;
  if (
    callee?.type === "MemberExpression" &&
    callee?.object?.type === "Identifier" &&
    callee?.object?.name === "p" &&
    callee?.property?.type === "Identifier" &&
    callee.property.name === "pgTable"
  ) return true;
  return false;
}

function camelToKebab(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function camelToPascal(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/** 从单个 dbschema 文件提取所有 pgTable */
function extractTables(schemaFile: string): TableInfo[] {
  if (!existsSync(schemaFile)) return [];
  const { program } = parseTsFile(schemaFile);
  const tables: TableInfo[] = [];

  traverseAst(program, (node) => {
    if (node.type !== "ExportNamedDeclaration") return;
    if (node.declaration?.type !== "VariableDeclaration") return;
    for (const decl of node.declaration.declarations) {
      if (!isPgTableCall(decl.init)) continue;
      if (decl.id?.type !== "Identifier") continue;
      const varName = decl.id.name;
      tables.push({
        varName,
        pascalName: camelToPascal(varName),
        fileName: camelToKebab(varName),
      });
    }
  });

  return tables;
}

// ---------------------------------------------------------------------------
// 渲染 tbschema 骨架
// ---------------------------------------------------------------------------

function generateTbschemaContent(table: TableInfo): string {
  const P = table.pascalName;
  return [
    "/** biome-ignore-all lint/style/useNamingConvention: 契约文件固定约束 */",
    MARKER,
    `import { Type as t } from "typebox";`,
    `import { type InferDTO, PaginationParamTBSchema, SortParamTBSchema } from "../utils";`,
    `import { ${P}RawInsert, ${P}RawSelect, ${P}RawUpdate } from "./raw";`,
    "",
    `export const ${P}TBSchema = {`,
    `  Response: t.Object({ ...${P}RawSelect.properties }),`,
    `  Create: t.Object({ ...t.Omit(${P}RawInsert, ["id", "createdAt", "updatedAt"]).properties }),`,
    `  Update: t.Partial(t.Object({ ...t.Omit(${P}RawInsert, ["id", "createdAt", "updatedAt"]).properties })),`,
    `  Patch: t.Partial(t.Object({ ...t.Omit(${P}RawInsert, ["id", "createdAt", "updatedAt"]).properties })),`,
    `  ListQuery: t.Object({`,
    `    ...t.Partial(${P}RawInsert).properties,`,
    `    ...PaginationParamTBSchema.properties,`,
    `    ...SortParamTBSchema.properties,`,
    `  }),`,
    `  ListResponse: t.Object({`,
    `    data: t.Array(t.Object({ ...${P}RawSelect.properties })),`,
    `    total: t.Number(),`,
    `  }),`,
    `} as const;`,
    "",
    `export type ${P}Contract = InferDTO<typeof ${P}TBSchema>;`,
    "",
  ].join("\n");
}

function hasMarker(content: string): boolean {
  // marker 在文件第 2 行(biome-ignore 在第 1 行)
  return content.split("\n").some((l) => l.startsWith(MARKER));
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export async function generateTbschemaCommand(opts: GenerateTbschemaOptions = {}): Promise<void> {
  if (!existsSync(CONFIG_PATH)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-gen.json，请先执行 api-gen info"));
    process.exit(1);
  }

  const raw = readFileSync(CONFIG_PATH);
  const config = JSON.parse(raw) as ApiGenRootConfig;

  if (!config.common) {
    pail.warn("未检测到公共合约层(common),没有 dbschema 可扫描");
    return;
  }

  const tbschemaRoot = config.common.tbschemaRoot;
  const tbschemaRawDir = config.common.tbschemaRawDir;

  if (!tbschemaRoot) {
    pail.warn("未配置 common.tbschemaRoot,请先执行 api-gen info");
    return;
  }
  if (!tbschemaRawDir) {
    pail.warn("未配置 common.tbschemaRawDir,请先执行 api-gen info");
    return;
  }

  const tbschemaRootAbs = resolve(CWD, tbschemaRoot);
  const rawDirAbs = resolve(CWD, tbschemaRawDir);

  const dbschemaFiles = config.common.dbschemaFiles;
  if (!dbschemaFiles.length) {
    pail.warn("未配置 dbschemaFiles(应在 packages/contract/src/drizzle/*.dbschema.ts)");
    return;
  }

  let totalTables = 0;
  let totalFiles = 0;
  let skipped = 0;

  for (const schemaFile of dbschemaFiles) {
    const schemaAbs = resolve(CWD, schemaFile);
    if (!existsSync(schemaAbs)) {
      pail.warn(`dbschema 文件不存在,跳过: ${chalk.dim(schemaFile)}`);
      continue;
    }

    const tables = extractTables(schemaAbs);
    if (!tables.length) continue;

    for (const table of tables) {
      if (opts.domain && table.fileName !== opts.domain) continue;

      // 检查 raw 文件是否存在(generate:tbschema 依赖 raw 已生成)
      const rawFile = join(rawDirAbs, `${table.fileName}.dbschema.raw.ts`);
      if (!existsSync(rawFile)) {
        pail.warn(
          `缺少 raw 文件: ${chalk.dim(rawFile)},请先运行 \`api-gen raw\``,
        );
        continue;
      }

      const outPath = join(tbschemaRootAbs, `${table.fileName}.tbschema.ts`);

      // 已存在无 marker → 手动维护,跳过
      if (existsSync(outPath)) {
        const existing = readFileSync(outPath);
        if (!hasMarker(existing)) {
          pail.warn(`跳过(手动维护): ${chalk.dim(outPath)}`);
          skipped++;
          continue;
        }
        if (hasMarker(existing) && !opts.force) {
          // 已有自动生成骨架,跳过(避免无意义覆盖)
          pail.debug(`已存在骨架,跳过: ${chalk.dim(outPath)}`);
          skipped++;
          continue;
        }
      }

      const content = generateTbschemaContent(table);
      writeFileSync(outPath, content);
      totalFiles++;
      console.log(chalk.dim(`  + ${table.fileName}.tbschema.ts  (${table.pascalName})`));
    }
    totalTables += tables.length;
  }

  if (totalFiles === 0 && skipped === 0) {
    pail.warn("未在任何 dbschema 文件中找到 pgTable 导出");
    return;
  }

  const summary = opts.force
    ? `已强制覆盖 ${totalFiles} 个 tbschema 骨架(共 ${totalTables} 张表)`
    : `生成了 ${totalFiles} 个 tbschema 骨架,跳过 ${skipped} 个(共 ${totalTables} 张表)`;
  pail.success(summary);
  console.log(chalk.dim("提示:这些骨架是用 XxxRawInsert/Select 派生的,业务字段需手调"));
}

export default async function generateTbschema(opts?: GenerateTbschemaOptions): Promise<void> {
  await generateTbschemaCommand(opts);
}
