import { readFileSync, writeFileSync, ensureDirSync } from "@visulima/fs";
import { existsSync } from "node:fs";
import { resolve, dirname, relative, join } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { parseTsFile, traverseAst } from "../utils/ast-scanner.js";
import type { ApiGenRootConfig } from "../types/api-gen.json.js";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

interface TableInfo {
  /** 导出变量名,如 "heroCardTable" */
  varName: string;
  /** Pascal 短名,如 "HeroCard" */
  pascalName: string;
  /** kebab-case 文件名,如 "hero-card" */
  fileName: string;
}

const CWD = process.cwd();
const CONFIG_PATH = resolve(CWD, ".vscode/api-gen.json");
const MARKER = "// Auto-generated by `api-gen raw` — do not edit manually.";

// ---------------------------------------------------------------------------
// AST 辅助
// ---------------------------------------------------------------------------

/** OXc 判断是否为 pgTable(...) 调用 */
function isPgTableCall(node: any): boolean {
  if (node?.type !== "CallExpression") return false;
  const callee = node.callee;
  if (callee?.type === "Identifier" && callee.name === "pgTable") return true;
  if (
    callee?.type === "MemberExpression" &&
    callee?.object?.type === "Identifier" &&
    callee?.object?.name === "p" &&
    callee?.property?.type === "Identifier" &&
    callee.property.name === "pgTable"
  ) return true;
  return false;
}

function camelToKebab(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function camelToPascal(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/** 从 dbschema 文件提取所有 pgTable 表 */
function extractTables(schemaFile: string): TableInfo[] {
  if (!existsSync(schemaFile)) return [];
  const { program } = parseTsFile(schemaFile);
  const tables: TableInfo[] = [];

  traverseAst(program, (node) => {
    if (node.type !== "ExportNamedDeclaration") return;
    if (node.declaration?.type !== "VariableDeclaration") return;
    for (const decl of node.declaration.declarations) {
      if (!isPgTableCall(decl.init)) continue;
      if (decl.id?.type !== "Identifier") continue;
      const varName = decl.id.name;
      tables.push({
        varName,
        pascalName: camelToPascal(varName),
        fileName: camelToKebab(varName),
      });
    }
  });

  return tables;
}

// ---------------------------------------------------------------------------
// 路径计算
// ---------------------------------------------------------------------------

/** 计算相对 import 路径(保证以 ./ 或 ../ 开头) */
function relImport(from: string, to: string): string {
  const p = relative(from, to).replace(/\\/g, "/").replace(/\.ts$/, "");
  return p.startsWith(".") ? p : `./${p}`;
}

/**
 * 决定 raw 文件 import dbschema 的方式(通用模式:优先桶,fallback 单文件)。
 *
 * 规则:看 dbschema 所在目录是否存在 index.ts 桶:
 * - 有桶 → 用桶路径(无后缀,ESM 解析默认 index.ts)
 * - 没桶 → 退到单文件路径(无后缀),并 warn 提示先跑 barrel
 *
 * 这个"先看桶再回退"是通用模式,后续其他命令(比如 link 引 controller 桶)
 * 都可以复用同款判断。
 *
 * @param fromDir  raw 文件所在目录(绝对路径)
 * @param sourceFile  源文件绝对路径(本场景为 dbschema,通用场景为任意源)
 */
function resolveBarrelImport(
  fromDir: string,
  sourceFile: string,
): { importPath: string; fromBarrel: boolean } {
  const sourceDir = dirname(sourceFile);
  const barrelIndex = join(sourceDir, "index.ts");

  if (existsSync(barrelIndex)) {
    // 桶路径(无后缀)
    const p = relative(fromDir, sourceDir).replace(/\\/g, "/");
    return { importPath: p.startsWith(".") ? p : `./${p}`, fromBarrel: true };
  }
  // fallback: 单文件路径
  return { importPath: relImport(fromDir, sourceFile), fromBarrel: false };
}

// ---------------------------------------------------------------------------
// 文件生成
// ---------------------------------------------------------------------------

/** 生成单个 raw 文件内容 */
function generateRawContent(
  table: TableInfo,
  schemaImportPath: string,
): string {
  return [
    MARKER,
    `import { createInsertSchema, createSelectSchema, createUpdateSchema } from "drizzle-orm/typebox";`,
    `import { ${table.varName} } from "${schemaImportPath}";`,
    "",
    `export const ${table.pascalName}RawSelect = createSelectSchema(${table.varName});`,
    `export const ${table.pascalName}RawInsert = createInsertSchema(${table.varName});`,
    `export const ${table.pascalName}RawUpdate = createUpdateSchema(${table.varName});`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export async function rawCommand(): Promise<void> {
  if (!existsSync(CONFIG_PATH)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-gen.json，请先执行 api-gen info"));
    process.exit(1);
  }

  const raw = readFileSync(CONFIG_PATH, { encoding: "utf-8" });
  const config = JSON.parse(raw) as ApiGenRootConfig;

  if (!config.common) {
    pail.warn("未检测到公共合约层(common),没有 drizzle schema 可扫描");
    return;
  }

  const tbschemaRawDir = config.common.tbschemaRawDir;
  if (!tbschemaRawDir) {
    pail.warn("配置中未设置 common.tbschemaRawDir,请先执行 api-gen info");
    return;
  }

  const rawDirAbs = resolve(CWD, tbschemaRawDir);
  ensureDirSync(rawDirAbs);

  const dbschemaFiles = config.common.dbschemaFiles;
  if (!dbschemaFiles.length) {
    pail.warn("未配置 dbschemaFiles,请检查 common.dbschemaFiles(应在 packages/contract/src/drizzle/)");
    return;
  }

  let totalTables = 0;
  let totalFiles = 0;
  let barrelHits = 0;
  let fallbacks = 0;

  for (const schemaFile of dbschemaFiles) {
    const schemaAbs = resolve(CWD, schemaFile);
    if (!existsSync(schemaAbs)) {
      pail.warn(`dbschema 文件不存在,跳过: ${chalk.dim(schemaFile)}`);
      continue;
    }

    const tables = extractTables(schemaAbs);
    if (!tables.length) continue;

    // 通用:先看桶,有就桶路径,没有 fallback 单文件路径
    const { importPath: schemaImportPath, fromBarrel } = resolveBarrelImport(rawDirAbs, schemaAbs);
    if (fromBarrel) barrelHits++; else fallbacks++;

    for (const table of tables) {
      const content = generateRawContent(table, schemaImportPath);
      const outPath = join(rawDirAbs, `${table.fileName}.dbschema.raw.ts`);
      writeFileSync(outPath, content);
      totalFiles++;
      console.log(chalk.dim(`  + ${table.fileName}.dbschema.raw.ts  (${table.varName})`));
    }
    totalTables += tables.length;
  }

  if (totalFiles === 0) {
    pail.warn("未在任何 dbschema 文件中找到 pgTable 导出");
    return;
  }

  const summary = `生成了 ${totalFiles} 个 raw 文件(共 ${totalTables} 张表),输出目录: ${chalk.underline(rawDirAbs)}`;
  pail.success(summary);

  // 路径策略说明
  if (barrelHits > 0 && fallbacks === 0) {
    console.log(chalk.dim(`  · ${barrelHits} 个 dbschema 全部走桶路径(已检测到 dbschema/index.ts)`));
  } else if (barrelHits > 0 && fallbacks > 0) {
    console.log(
      chalk.dim(
        `  · 桶路径: ${barrelHits} 个,fallback 单文件: ${fallbacks} 个(部分 dbschema 缺桶)`,
      ),
    );
  } else {
    console.log(
      chalk.yellow(
        `  · 全部 fallback 到单文件路径,建议先跑 ${chalk.cyan("api-gen barrel")} 生成 dbschema 桶,再跑 raw`,
      ),
    );
  }
}

export default async function raw(): Promise<void> {
  await rawCommand();
}
