import { readFileSync, writeFileSync, ensureDirSync } from "@visulima/fs";
import { existsSync } from "node:fs";
import { resolve, dirname, relative, join } from "@visulima/path";
import chalk from "@visulima/colorize";
import { pail } from "@visulima/pail";
import { parseTsFile, traverseAst } from "../utils/ast-scanner.js";
import type { ApiGenRootConfig } from "../types/api-gen.json.js";

// ---------------------------------------------------------------------------
// 类型
// ---------------------------------------------------------------------------

interface TableInfo {
  /** 导出变量名，如 "heroCardTable" */
  varName: string;
  /** Pascal 短名，如 "HeroCard" */
  pascalName: string;
  /** kebab-case 文件名，如 "hero-card" */
  fileName: string;
}

// ---------------------------------------------------------------------------
// 常量
// ---------------------------------------------------------------------------

const CWD = process.cwd();
const CONFIG_PATH = resolve(CWD, ".vscode/api-gen.json");

// ---------------------------------------------------------------------------
// 辅助函数
// ---------------------------------------------------------------------------

/** OXc 判断是否为 pgTable(...) 调用（p.pgTable / pgTable） */
function isPgTableCall(node: any): boolean {
  if (node?.type !== "CallExpression") return false;
  const callee = node.callee;
  if (callee?.type === "Identifier" && callee.name === "pgTable") return true;
  if (
    callee?.type === "MemberExpression" &&
    callee.property?.type === "Identifier" &&
    callee.property.name === "pgTable"
  ) return true;
  return false;
}

/** camelCase → kebab-case（自动去掉 Table 后缀） */
function camelToKebab(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/** camelCase → PascalCase（自动去掉 Table 后缀） */
function camelToPascal(name: string): string {
  const base = name.endsWith("Table") ? name.slice(0, -5) : name;
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/** 从 schema 文件提取所有 pgTable 表 */
function extractTables(schemaFile: string): TableInfo[] {
  if (!existsSync(schemaFile)) return [];
  const { program } = parseTsFile(schemaFile);
  const tables: TableInfo[] = [];

  traverseAst(program, (node) => {
    if (node.type !== "ExportNamedDeclaration") return;
    if (node.declaration?.type !== "VariableDeclaration") return;
    for (const decl of node.declaration.declarations) {
      if (!isPgTableCall(decl.init)) continue;
      if (decl.id?.type !== "Identifier") continue;
      const varName = decl.id.name;
      tables.push({
        varName,
        pascalName: camelToPascal(varName),
        fileName: camelToKebab(varName),
      });
    }
  });

  return tables;
}

/** 计算相对 import 路径（保证以 ./ 或 ../ 开头） */
function relImport(from: string, to: string): string {
  const p = relative(from, to).replace(/\\/g, "/").replace(/\.ts$/, "");
  return p.startsWith(".") ? p : `./${p}`;
}

/** 生成单个 raw 文件内容 */
function generateRawContent(
  table: TableInfo,
  schemaImportPath: string,
  utilsImportPath: string,
): string {
  return [
    "// Auto-generated by `api-gen raw` — do not edit manually.",
    `import { ${table.varName} } from "${schemaImportPath}";`,
    `import { spread } from "${utilsImportPath}";`,
    "",
    `export const ${table.pascalName}RawSelect = spread(${table.varName}, "select");`,
    `export const ${table.pascalName}RawInsert = spread(${table.varName}, "insert");`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export async function rawCommand(): Promise<void> {
  if (!existsSync(CONFIG_PATH)) {
    console.error(chalk.red("缺少配置文件 .vscode/api-gen.json，请先执行 api-gen init"));
    process.exit(1);
  }

  const raw = readFileSync(CONFIG_PATH, { encoding: "utf-8" });
  const config = JSON.parse(raw) as ApiGenRootConfig;

  if (!config.common) {
    pail.warn("未检测到公共合约层（common），没有 drizzle schema 可扫描");
    return;
  }

  const dtoDir = config.common.dtoDir;
  if (!dtoDir) {
    pail.warn("配置中未设置 dtoDir，请编辑 .vscode/api-gen.json 的 common.dtoDir");
    return;
  }

  const dtoDirAbs = resolve(CWD, dtoDir);
  const rawDir = join(dtoDirAbs, "raw");
  ensureDirSync(rawDir);

  // 计算 utils 相对路径（从 rawDir → dtoDir/../utils）
  const utilsDir = resolve(dtoDirAbs, "..", "utils");
  const utilsImportPath = relImport(rawDir, utilsDir);

  const schemaFiles = config.common.schemaFiles;
  if (!schemaFiles.length) {
    pail.warn("未配置 schemaFiles，请在 common.schemaFiles 中指定 drizzle schema 文件路径");
    return;
  }

  let totalTables = 0;
  let totalFiles = 0;

  for (const schemaFile of schemaFiles) {
    const schemaAbs = resolve(CWD, schemaFile);
    if (!existsSync(schemaAbs)) {
      pail.warn(`schema 文件不存在，跳过：${chalk.dim(schemaFile)}`);
      continue;
    }

    const tables = extractTables(schemaAbs);
    if (!tables.length) continue;

    const schemaImportPath = relImport(rawDir, schemaAbs);

    for (const table of tables) {
      const content = generateRawContent(table, schemaImportPath, utilsImportPath);
      const outPath = join(rawDir, `${table.fileName}.raw.ts`);
      writeFileSync(outPath, content);
      totalFiles++;
      console.log(chalk.dim(`  + ${table.fileName}.raw.ts  (${table.varName})`));
    }
    totalTables += tables.length;
  }

  if (totalFiles === 0) {
    pail.warn("未在任何 schema 文件中找到 pgTable 导出");
    return;
  }

  const summary = `生成了 ${totalFiles} 个 raw 文件（共 ${totalTables} 张表），输出目录：${chalk.underline(rawDir)}`;
  pail.success(summary);
  console.log(chalk.dim("提示：这些文件是纯自动生成的，随时可以安全地重新运行 `api-gen raw` 覆盖"));
}

export default async function raw(): Promise<void> {
  await rawCommand();
}
