import { describe, it, expect, beforeAll, afterAll } from "bun:test";
import { mkdirSync, writeFileSync, rmSync, readFileSync, existsSync } from "node:fs";
import { join, resolve, relative } from "node:path";

const ROOT = resolve(import.meta.dir, "../..");

let importSeq = 0;
async function freshImport(p: string) {
  return await import(`${p}?cb=${importSeq++}`);
}
async function runBarrel(cwd: string) {
  const prev = process.cwd();
  process.chdir(cwd);
  try {
    // 命令模块路径相对 __tests__/ 文件位置解析(参考 workflow.test.ts 的调用方式)
    const m = await freshImport("../commands/barrel.js");
    await m.barrelCommand({});
  } finally {
    process.chdir(prev);
  }
}

describe("路径形式组：组根不直接出现孙级路径", () => {
  const root = join(ROOT, ".test-tmp/barrel-no-grandchildren");

  beforeAll(() => {
    if (existsSync(root)) rmSync(root, { recursive: true, force: true });
    mkdirSync(root, { recursive: true });
    writeFileSync(join(root, "package.json"), JSON.stringify({ name: "no-grandchildren" }));

    // 组根散文件 + 一级子目录 + 孙级散文件 + 孙级子目录
    mkdirSync(join(root, "src/hooks"), { recursive: true });
    mkdirSync(join(root, "src/utils/nested"), { recursive: true });
    writeFileSync(join(root, "src/foo.ts"), "export const foo = 1;");
    writeFileSync(join(root, "src/hooks/use-bar.ts"), "export const useBar = 1;");
    writeFileSync(join(root, "src/utils/page.ts"), "export const paginate = 1;");
    writeFileSync(
      join(root, "src/utils/nested/deep.ts"),
      "export const deep = 1;\nexport type Deep = { id: string };",
    );

    mkdirSync(join(root, ".vscode"), { recursive: true });
    writeFileSync(
      join(root, ".vscode/api-config.json"),
      JSON.stringify({
        exportIndex: {
          includes: ["./src"],
          "./src": [],
        },
      }, null, 2),
    );
  });

  afterAll(() => {
    if (existsSync(root)) rmSync(root, { recursive: true, force: true });
  });

  it("src/index.ts 只引用一级,孙级路径不直接出现", async () => {
    await runBarrel(root);

    const top = readFileSync(join(root, "src/index.ts"), "utf-8");

    // 1) 一级子目录应被引用
    expect(top).toContain('from "./utils"');
    expect(top).toContain('from "./hooks"');

    // 2) 组根散文件应被引用
    expect(top).toContain('from "./foo"');

    // 3) 孙级目录路径不直接出现在组根
    expect(top).not.toContain('from "./utils/nested"');
    expect(top).not.toContain('from "./utils/page"');
    expect(top).not.toContain('from "./hooks/use-bar"');

    // 4) 孙级散文件路径不直接出现在组根
    expect(top).not.toContain("deep.ts");
    expect(top).not.toContain("page.ts");
    expect(top).not.toContain("use-bar.ts");

    // 5) 父级的 from "./utils" 行包含 paginate(一级叶子)和 deep(孙级符号经级联)
    const utilsLine = top.match(/export\s*\{[^}]*\}\s*from\s*"\.\/utils"/)?.[0] ?? "";
    expect(utilsLine).toContain("paginate");
    expect(utilsLine).toContain("deep");
  });

  it("中间层 src/utils/index.ts 仍 re-export 直接子目录 barrel", async () => {
    const utilsIdx = readFileSync(join(root, "src/utils/index.ts"), "utf-8");

    // 中间层 re-export 直接子目录
    expect(utilsIdx).toContain('from "./nested"');

    // 中间层 re-export 直接散文件
    expect(utilsIdx).toContain('from "./page"');

    // 中间层 from "./nested" 行包含孙级符号
    const nestedLine = utilsIdx.match(/export\s*\{[^}]*\}\s*from\s*"\.\/nested"/)?.[0] ?? "";
    expect(nestedLine).toContain("deep");
  });

  it("孙级 index.ts 只 re-export 直接叶子", async () => {
    const nestedIdx = readFileSync(join(root, "src/utils/nested/index.ts"), "utf-8");
    expect(nestedIdx).toContain("deep");
    expect(nestedIdx).toContain("Deep");
  });

  it("每个 index.ts 都带自动标记,幂等", async () => {
    const top = readFileSync(join(root, "src/index.ts"), "utf-8");
    const utilsIdx = readFileSync(join(root, "src/utils/index.ts"), "utf-8");
    const nestedIdx = readFileSync(join(root, "src/utils/nested/index.ts"), "utf-8");

    for (const c of [top, utilsIdx, nestedIdx]) {
      expect(c.startsWith("// Auto-generated by `api-gen barrel` — do not edit manually.")).toBe(true);
    }
  });
});
